### ISSUE TITLE
Add pressed_letter attribute to player struct

### ISSUE THREAD

**Issue by StrayMarimo** [StrayMarimo/CatchThePhrase#5]
We should also keep track of the letters that were pressed already by a player.
### Todo:

- [x]  add this field for the player struct (can be called letters_pressed)
- [ ]  add function: `char* AddLetter(char letter);`
- [x]  add function: `bool isLetterPressed(char letter)`

**Comment by jeromefloresss** [comment]
Suggestion:
1. Initialize array of the english alphabet.
2. Use this array to check if letter is pressed. This can be done by changing letters already guessed to another character (e.g. " * "). This way dawa dae na maggamit ning dynamic array :smile:

**Comment by StrayMarimo** [comment]
> Suggestion:
> 
> 1. Initialize array of the english alphabet.
> 2. Use this array to check if letter is pressed. This can be done by changing letters already guessed to another character (e.g. " * "). Make function na lang na like: if(letter_pressed == alphabet[i]) //for unguessed letter. tho magamit ning loop to iterate each letter para mahanap si letter. Okay man garo arog kani implementation? This way dawa dae na maggamit ning dynamic array 😄 . Tots?

yepyep, implement mo na hehe
